### ISSUE TITLE
PANIC; Mix_OpenAudio failed! & assertion "0" failed!

### ISSUE THREAD

**Issue by oocyberkevinoo** [derrekr/srb2_3ds#1]
just after "SoundDriverInit!", just have a PANIC notification with that inside : 

Mix_OpenAudio failed!
assertion "0" failed!
file "D:/3DS/repos/srb2_3ds/source/nds/nds_utilis.c", line 120, function: NDS3D_driverPanic

System : New 3DS 11.8.0-41 E on latest Luma update (9.1 ?)

**Comment by derrekr** [comment]
Thanks for reporting this issue!
Have you dumped your 3DS' DSP firmware (eg by using DspDump)?
Maybe dspfirm.cdc is missing.

**Comment by oocyberkevinoo** [comment]
No, I haven't, certainly will correct the problem, I'll check that in a few moments, 
thanks for your work and answer ;)

**Comment by oocyberkevinoo** [comment]
Worked, but now, the screen stay black as the game is correctly running :/

**Comment by oocyberkevinoo** [comment]
Just tried,no more problems, game run nicely, Good job ;) 
Just hope we could have a 60 framerate 100% stable, but everything else is perfect ;)

**Comment by derrekr** [comment]
Nice!
