### ISSUE TITLE
Add the last supported version to the instructions 

### ISSUE THREAD

**Issue by jlcmes** [derrekr/srb2_3ds#14]
Hi, I tried the port with the last version of the game that is in the archived versions section of the main website.

I would add on the instructions of the README the following steps:
Download the file https://files.srb2.org/srb2.org/history/SRB2-v2125-x64-Installer.exe
Install it or unpack with 7z or Winrar to a temporary folder.
Copy all the Dta and Srb files (all the files with the exception of the exe and txt) to the /3ds/srb2_3ds/

This version seems to be more updated that the one of the tutorial.

Thank you for your work!

**Comment by derrekr** [comment]
Probably should finally update the README and make the installation steps more clear.... Ofc the best thing would be if the game files were bundled with the 3dsx/cia

**Comment by derrekr** [comment]
Simplified the instructions in the README.
