### ISSUE TITLE
Minor graphic issue with score talley

### ISSUE THREAD

**Issue by cheatfreak47** [derrekr/srb2_3ds#4]
The score talley screen is supposed to display a copy of the last in-game frame behind the score talley, but this port only shows a black frame, probably a known issue, or not implemented for whatever reason

**Comment by derrekr** [comment]
That's probably because my "HW Graphics Driver" for SRB2 doesn't implement the "pfnReadRect" call. I might look into that, but it doesn't seem very important.

**Comment by derrekr** [comment]
I think this is a very minor issue and has no impact on the actual gameplay. Thus, I'm closing the issue as won't fix.
