### ISSUE TITLE
Wad Support 

### ISSUE THREAD

**Issue by jcmejia** [derrekr/srb2_3ds#6]
Does Srb2 3ds Support Wads for custom Characters

**Comment by derrekr** [comment]
Yes, SRB2 3DS has support for loading WAD files. See Method 2) Option b) here https://wiki.srb2.org/wiki/WAD_file#Loading_WAD_files for a compatilbe WAD loading method.
Note that MD2 character mods are currently not supported due to lack of MD2 rendering.
