### ISSUE TITLE
The Music Isn't Working!

### ISSUE THREAD

**Issue by Garebear1903** [derrekr/srb2_3ds#9]
The Whole Game, But The Music Is Not Even There! I Even Got The Updated Version Of The Song, And Yet Does Not Work!

**Comment by derrekr** [comment]
Not all music formats are supported by srb2_3ds.
The original srb2 levels only use supported formats.
What mods are you using?
Do you know what music format is causing the issue?

**Comment by Garebear1903** [comment]
I don't know, it say "áERROR: Music stjr could not be loaded!" It all of the Songs/Music by the way. Oh and Sounds too, and the sounds have a error code of *0xD8R0A7EA* DSP init failed.

**Comment by derrekr** [comment]
Have you dumped the DSP firmware? "DSP init failed" means that the HW responsible for audio could not be initialized.

**Comment by Garebear1903** [comment]
Oh i don't know how to do that, dumping DSP firmware how you do it?

**Comment by Oreo639** [comment]
https://github.com/zoogie/dsp1

**Comment by Garebear1903** [comment]
Ok thanks, can you give a tutorial too?

**Comment by derrekr** [comment]
Install the DSP1.cia file and launch it.

**Comment by Garebear1903** [comment]
Ok thanks for the help!

**Comment by Garebear1903** [comment]
It work! Im happy now! Thank you for helping me a lot! Should i close this issue or no?

**Comment by Oreo639** [comment]
Yep.

**Comment by Garebear1903** [comment]
Thanks Now This Issue Is CLOSED
